project_id = "soeimcfkcikyalhjiaru"

[functions.create-pix-charge]
verify_jwt = false

[functions.check-payment-status]
verify_jwt = false

[functions.payment-webhook]
verify_jwt = false

[functions.create-billing]
verify_jwt = false

[functions.abacate-webhook]
verify_jwt = false
